"""initial schema: tenants + staging tables + mart indexes

Revision ID: 0001
Revises:
Create Date: 2026-05-24

Parity with the original data-generator/init.sql (now deleted), with two
additions:

  1. Indexes the Part 3 §9.3 mart SQL needs:
       - (tenant_id, date) on stg_google_ads
       - (tenant_id, day)  on stg_meta_ads
       - partial indexes on dim_client's two join keys
  2. Schema/table creation in a single, ordered Alembic step rather than a
     `CREATE … IF NOT EXISTS` bootstrap.

Row-Level Security policies (Part 1 §2 / Part 2 §6) land in a follow-up
migration once the FastAPI app exists and we have a non-superuser role to
enforce them against.

Written by hand (not autogenerated) — there are no SQLAlchemy models yet.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- Operational store: tenant identity (Part 1 §2.5) ----
    op.execute("""
        CREATE TABLE tenants (
            id          TEXT PRIMARY KEY,
            name        TEXT NOT NULL,
            created_at  TIMESTAMP NOT NULL DEFAULT NOW()
        );
    """)

    # ---- Staging schema (warehouse-side) ----
    op.execute("CREATE SCHEMA staging;")

    # dim_client: campaign-to-client mapping (Part 3 §3.3).
    # Rows have EITHER ga_campaign_id OR meta_campaign_name set, never both —
    # so the lookup indexes are partial to skip the NULL rows.
    op.execute("""
        CREATE TABLE staging.dim_client (
            client_id                          TEXT NOT NULL,
            client_name                        TEXT NOT NULL,
            ga_campaign_id                     TEXT,
            meta_campaign_name                 TEXT,
            expected_revenue_from_acquisition  NUMERIC(18, 2),
            FOREIGN KEY (client_id) REFERENCES tenants(id)
        );
    """)
    op.execute("""
        CREATE INDEX dim_client_ga_lookup
            ON staging.dim_client (client_id, ga_campaign_id)
            WHERE ga_campaign_id IS NOT NULL;
    """)
    op.execute("""
        CREATE INDEX dim_client_meta_lookup
            ON staging.dim_client (client_id, meta_campaign_name)
            WHERE meta_campaign_name IS NOT NULL;
    """)

    # stg_google_ads: one row per campaign per day (Part 3 §3.2).
    op.execute("""
        CREATE TABLE staging.stg_google_ads (
            tenant_id      TEXT          NOT NULL,
            campaign_id    TEXT          NOT NULL,
            campaign_type  TEXT,
            date           DATE          NOT NULL,
            spend          NUMERIC(18, 2),
            impressions    BIGINT,
            clicks         BIGINT,
            conversions    NUMERIC(18, 2),
            loaded_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
            FOREIGN KEY (tenant_id) REFERENCES tenants(id)
        );
    """)
    # (tenant_id, date) is the hot path for every mart query and dashboard call.
    op.execute("""
        CREATE INDEX stg_google_ads_tenant_date
            ON staging.stg_google_ads (tenant_id, date);
    """)

    # stg_meta_ads: one row per DMA-campaign per day (Part 3 §3.2).
    op.execute("""
        CREATE TABLE staging.stg_meta_ads (
            tenant_id      TEXT          NOT NULL,
            campaign_name  TEXT          NOT NULL,
            dma            TEXT          NOT NULL,
            day            DATE          NOT NULL,
            spend          NUMERIC(18, 2),
            reach          BIGINT,
            impressions    BIGINT,
            clicks         BIGINT,
            result_type    TEXT,
            results        NUMERIC(18, 2),
            loaded_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
            FOREIGN KEY (tenant_id) REFERENCES tenants(id)
        );
    """)
    op.execute("""
        CREATE INDEX stg_meta_ads_tenant_day
            ON staging.stg_meta_ads (tenant_id, day);
    """)


def downgrade() -> None:
    # Reverse FK order: fact tables first, then dim_client, then tenants.
    op.execute("DROP TABLE IF EXISTS staging.stg_meta_ads;")
    op.execute("DROP TABLE IF EXISTS staging.stg_google_ads;")
    op.execute("DROP TABLE IF EXISTS staging.dim_client;")
    op.execute("DROP SCHEMA IF EXISTS staging;")
    op.execute("DROP TABLE IF EXISTS tenants;")
